In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np.random.seed(50)
data=pd.read_csv('classification_train.csv')
print(data.head(10))
m=len(data)
n=len(data.columns)
data_of_each_individual_x={}
for i in range(0,(n-2)):
    data_of_each_individual_x[i]=data.iloc[:,(i+2)]
print(data_of_each_individual_x)

   Unnamed: 0  label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0           0      8       0       0       0       0       0       0       0   
1           1      4       0       0       0       0       0       0       0   
2           2      1       0       0       0       0       0       0       0   
3           3      8       0       0       0       0       0       0       0   
4           4      2       0       0       0       0       1       0       3   
5           5      0       0       0       0       0       0       0       0   
6           6      7       0       0       0       0       0       0       0   
7           7      4       0       0       0       0       0       0       0   
8           8      1       0       0       0       0       0       0       4   
9           9      7       0       0       0       0       0       0       0   

   pixel8  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0       

In [3]:
print(m)
print(n)

30000
786


In [4]:
for i in range((n-2)):    
    data_of_each_individual_x[i]/=255
print(data_of_each_individual_x)

{0: 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
29995    0.0
29996    0.0
29997    0.0
29998    0.0
29999    0.0
Name: pixel1, Length: 30000, dtype: float64, 1: 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
29995    0.0
29996    0.0
29997    0.0
29998    0.0
29999    0.0
Name: pixel2, Length: 30000, dtype: float64, 2: 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
29995    0.0
29996    0.0
29997    0.0
29998    0.0
29999    0.0
Name: pixel3, Length: 30000, dtype: float64, 3: 0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...   
29995    0.000000
29996    0.000000
29997    0.000000
29998    0.000000
29999    0.003922
Name: pixel4, Length: 30000, dtype: float64, 4: 0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.003922
           ...   
29995    0.000000
29996    0.000000
29997    0.000000
29998    0.0039

In [5]:
data_of_all_x={}
for i in range(m):
    loop_array=data.iloc[i]
    data_of_all_x[i]=loop_array[2:n]
print(data_of_all_x[1])

pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Name: 1, Length: 784, dtype: int64


In [6]:
z={}
w=np.zeros((n-2))
y_hat=np.zeros(m)
b=0
for i in range(m):
    z[i]=np.dot(w,data_of_all_x[i])+b
    y_hat[i]=(1+np.exp(-z[i]))**(-1)
print(y_hat)

[0.5 0.5 0.5 ... 0.5 0.5 0.5]


In [7]:
individual_classification_data={}
for i in range(10):
    individual_classification_data[i]=data.iloc[:,1].copy()

In [8]:
for i in range(10):
    for j in range(m):
        if(individual_classification_data[i][j]==i):
            individual_classification_data[i][j]=1
        else:
            individual_classification_data[i][j]=0
    print(individual_classification_data[i])

0        0
1        0
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    0
29998    0
29999    0
Name: label, Length: 30000, dtype: int64
0        0
1        0
2        1
3        0
4        0
        ..
29995    0
29996    0
29997    0
29998    0
29999    0
Name: label, Length: 30000, dtype: int64
0        0
1        0
2        0
3        0
4        1
        ..
29995    0
29996    0
29997    0
29998    0
29999    0
Name: label, Length: 30000, dtype: int64
0        0
1        0
2        0
3        0
4        0
        ..
29995    1
29996    0
29997    0
29998    0
29999    0
Name: label, Length: 30000, dtype: int64
0        0
1        1
2        0
3        0
4        0
        ..
29995    0
29996    1
29997    0
29998    1
29999    0
Name: label, Length: 30000, dtype: int64
0        0
1        0
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    0
29998    0
29999    0
Name: label, Length: 30000, dtype: int64
0        0
1        0
2     

In [9]:
cost_data={}
w_data={}
b_data={}
for i in range(10):
    for no_of_iterations in range(50):
        data_of_grad_w=0
        grad_b=(1/m)*(np.sum(y_hat-individual_classification_data[i]))
        temp_w=np.zeros((n-2))
        for j in range((n-2)):
            data_of_grad_w=((1/m)*((np.sum((y_hat-individual_classification_data[i])*data_of_each_individual_x[j]))))
            temp_w[j]=w[j]-(0.0005)*data_of_grad_w
        temp_b=b-((0.0005)*(grad_b))
        w=temp_w
        b=temp_b
        for k in range(m):
            y_hat[k]=((1+np.exp(-np.dot(w,data_of_all_x[k])+b))**(-1))
        print(no_of_iterations+1)
        cost_function=-(1/m)*(np.sum((individual_classification_data[i]*(np.log(y_hat)))+((1-individual_classification_data[i])*(np.log(1-y_hat)))))
        print(cost_function)
        if((no_of_iterations+1)==50):
            cost_data[i]=cost_function
            w_data[i]=w
            b_data[i]=b

1
0.5313737266461305
2
0.40394319599867956
3
0.32165977619068586
4
0.2910125888142705
5
0.2765579793639598
6
0.26415673665314765
7
0.25332684027374835
8
0.24379436167034244
9
0.23535083404575016
10
0.22783183029361456
11
0.22110441875060932
12
0.21505936830645328
13
0.20960584835041532
14
0.2046676588738969
15
0.20018042969250657
16
0.19608947256239645
17
0.19234809469068126
18
0.1889162520142661
19
0.18575946065120272
20
0.18284790912295615
21
0.1801557293343481
22
0.17766039460612568
23
0.1753422202866973
24
0.17318394774072216
25
0.17117039647002052
26
0.1692881721599018
27
0.1675254208127095
28
0.16587162099863453
29
0.1643174077396864
30
0.16285442273179696
31
0.16147518656630686
32
0.1601729893842431
33
0.15894179702248173
34
0.15777617021950743
35
0.15667119486317757
36
0.15562242160199155
37
0.1546258134194297
38
0.1536776999995754
39
0.15277473790077273
40
0.1519138757099677
41
0.15109232347963436
42
0.15030752585664298
43
0.14955713840200824
44
0.14883900667532493
45
0.148151

17
0.1746726936080768
18
0.17083711032669632
19
0.16749012008552908
20
0.16454006484234804
21
0.16191618450735148
22
0.15956321983700011
23
0.15743752235046576
24
0.15550423439349004
25
0.1537352277231713
26
0.15210758178679756
27
0.1506024486932463
28
0.14920419768278304
29
0.14789976356858406
30
0.146678145523629
31
0.14553001779867275
32
0.14444742459456314
33
0.14342353881099498
34
0.14245246972655362
35
0.14152910849191985
36
0.14064900308982853
37
0.13980825644109582
38
0.13900344282975427
39
0.13823153893132092
40
0.13748986656146472
41
0.13677604489230405
42
0.1360879503635366
43
0.13542368288399972
44
0.134781537204032
45
0.13415997856062628
46
0.13355762187096254
47
0.13297321388672872
48
0.13240561783011853
49
0.13185380011888853
50
0.1313168188571984
1
0.5778952154630884
2
0.5249631488020541
3
0.47892418944584697
4
0.43918376428112776
5
0.4052105843164204
6
0.37646322094241974
7
0.3523394971762947
8
0.3321622309038778
9
0.31523168373039917
10
0.30089998576019583
11
0.288618

In [10]:
print(cost_data)
print(w_data)
print(b_data)

{0: 0.14510662083719048, 1: 0.08028296945254955, 2: 0.2084870191815489, 3: 0.1669213012581047, 4: 0.23207799600447493, 5: 0.15631571209745904, 6: 0.25388536874172013, 7: 0.1313168188571984, 8: 0.15125330693756903, 9: 0.1319492625861582}
{0: array([ 9.28095928e-09,  6.56623244e-08,  5.83199757e-07,  1.04157494e-06,
        4.42328164e-07, -3.93675143e-07, -3.46616111e-07,  7.18583344e-06,
        2.49914380e-05,  1.60535229e-05, -5.02034133e-05, -6.86701201e-05,
       -1.40799719e-04, -1.86052789e-04, -1.83371718e-04, -1.81720682e-04,
       -7.20145223e-05, -2.29217751e-05, -2.55003519e-05,  2.14588331e-05,
        1.34385535e-05, -2.20800767e-06, -5.53081381e-06, -3.55511104e-06,
       -7.40656323e-07, -4.42284647e-08, -2.62480946e-07, -1.70655026e-08,
        1.61812362e-08,  4.78763192e-08,  1.16223797e-06,  4.32445123e-06,
        3.13036770e-06,  1.15290761e-05,  6.57514281e-05,  1.55501489e-04,
        2.01565303e-04,  1.45191772e-04,  1.74713154e-05, -3.58135011e-05,
       -1

In [11]:
testdata=pd.read_csv('classification_test.csv')
print(testdata.head(10))
test_m=len(testdata)
test_n=len(testdata.columns)
data_of_test_individual_x={}
for i in range(0,((test_n)-1)):
    data_of_test_individual_x[i]=testdata.iloc[:,(i+1)]
    data_of_test_individual_x[i]/=255
print(data_of_test_individual_x)

     ids  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0  25672       0       0       0       0       0       0       0       9   
1  59964       0       0       0       0       0       0       0       0   
2  66230       0       0       0       0       0       0      14      53   
3  50801       0       0       0       0       0       0       0       0   
4  83307       0       0       0       0       0       0       0       0   
5  91787       0       0       0       0       0      44     105      44   
6  58429       0       0       0       0       0       0       0       0   
7  99131       0       0       0       0       0       0       0       1   
8  80125       0       0       0       0       0       0       0       0   
9  25082       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1      

In [ ]:
print(test_m)
print(test_n)

In [12]:
data_of_all_test_x={}
for i in range(test_m):
    loop_array=testdata.iloc[i]
    data_of_all_test_x[i]=loop_array[1:n]
print(data_of_all_test_x[1])

pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Name: 1, Length: 784, dtype: int64


In [13]:
max_sigmoid=np.zeros(test_m)
y_pred=np.zeros(test_m)
for i in range(test_m):
    max_sigmoid[i]=max((1+np.exp(-(np.dot(w_data[0],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[1],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[2],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[3],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[4],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[5],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[6],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[7],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[8],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[9],data_of_all_x[i])+b)))**(-1))
    y_pred[i]=int(np.argmax([(1+np.exp(-(np.dot(w_data[0],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[1],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[2],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[3],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[4],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[5],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[6],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[7],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[8],data_of_all_x[i])+b)))**(-1),(1+np.exp(-(np.dot(w_data[9],data_of_all_x[i])+b)))**(-1)]))

In [14]:
print(max_sigmoid)
print(y_pred)

[0.18737365 0.14143759 0.34682759 ... 0.43041564 0.72633816 0.07770203]
[7. 4. 1. ... 7. 8. 4.]
