In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [60]:
#read the data 
# reading the data
df = pd.read_csv('classification_train.csv')
temp1 = df.to_numpy()
X_train = temp1[5000:30001,2:787]
X_test = temp1[1:5001,2:787]
y_train = temp1[5000:30001,0:2]
y_test = temp1[1:5001,0:2]
print(X_train.shape)
print(X_test.shape)
print (y_train.shape)
print(y_test.shape)


(25000, 784)
(5000, 784)
(25000, 2)
(5000, 2)


In [61]:
def zscore(X_in):
    mu     = np.mean(X_in, axis=0)                 
    sigma  = np.std(X_in, axis=0)                
    X_norm = (X_in - mu) / sigma
    X_op = X_in/ 255
    return X_norm ,mu,sigma
a,mean,std = zscore(X_train)
print(a.shape)


(25000, 784)


In [23]:
#making 10 different ytrains sets
m = y_train.shape[0]
y_ntrain = y_train[:,1:2]
for i in range(10) :
    y_new = np.zeros(m)
    for j in range(m):
        if y_train[j,1] == i:
            y_new[j] = 1
        else:
            y_new[j] = 0 
    y_ntrain = np.hstack((y_ntrain, np.atleast_2d(y_new).T))
print(y_ntrain.shape)
print(y_ntrain[:,0:11])

(25000, 11)
[[3. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 ...
 [9. 0. 0. ... 0. 0. 1.]
 [4. 0. 0. ... 0. 0. 0.]
 [6. 0. 0. ... 0. 0. 0.]]


In [5]:
# computoing the sigmoid fucntion
def compute_sigmoid(z):
    a = 1/(1+np.exp(-z))
    return a



In [6]:
# computing the cost function
def compute_cost(x,y,w,b):
    m = x.shape[0]
    z_i = np.matmul(x,w) + b
    f_wb = compute_sigmoid(z_i)
    cost = -(1/m)*np.sum(y*(np.log(f_wb)) + (1-y)*(np.log(1-f_wb)))
    return cost

In [7]:
df = pd.DataFrame(y_train)
df

0  1
0       5000  3
1       5001  3
2       5002  5
3       5003  9
4       5004  5
...      ... ..
24995  29995  3
24996  29996  4
24997  29997  9
24998  29998  4
24999  29999  6

[25000 rows x 2 columns]

In [8]:
def compute_gradient(x,y,w,b):
       
    m,n = x.shape          
    dj_dw = np.zeros((m,n))
    dj_db = np.zeros(m)
    c = compute_sigmoid((np.matmul(x,w) + b)) - y
    for i in range(m):                             
        dj_dw[i] = c[i]*x[i]
    dj_dw = np.sum(dj_dw,axis = 0)/m
    dj_db = np.sum(c)/m
                                 
        
        
    return (dj_dw,dj_db)


In [9]:
def compute_gradient_descent(x,y,w_in,b_in,alpha,no_iters,gradient,cost):
    cost_store=[]
    w=w_in
    b = b_in
    for i in range(no_iters):
        dj_dw,dj_db = gradient(x,y,w,b)
        w = w - alpha*dj_dw
        b = b - (alpha*dj_db)
        coste=cost(x,y,w,b)
        cost_store.append(coste)
        print(coste)
    return w,b


In [53]:
m,n = X_train.shape
b_init = 0
w_init = np.zeros(n)
w_outr = np.zeros((10,784))
b_outr = np.zeros((10,1))
X = zscore(X_train)
for i in range(1,11):
    no_iters = 200
    if(i==9):
        alpha=0.01
    else:
        alpha=0.05
    w_out,b_out = compute_gradient_descent(X,y_ntrain[:,i],w_init,b_init,alpha,no_iters,compute_gradient,compute_cost)
    if(no_iters%25==0):
        print(f"the final w,b for {i-1} th iteration = {w_out},{b_out} ")
    w_outr[i-1] = w_out
    b_outr[i-1] = b_out
    


0.6387232949101374
0.6102788084889152
0.5914632698871608
0.5757509336578294
0.5627505711212026
0.5510577451153659
0.5407931374674979
0.5314077725141714
0.522862066638163
0.5149101411656953
0.5074712148672201
0.5004302482409431
0.4937265137767388
0.48730442574383676
0.4811279657995403
0.4751686479926187
0.4694057630829604
0.4638230097097155
0.45840743726338884
0.45314832102244657
0.4480365402995625
0.4430641522114694
0.43822410332266243
0.4335100480294611
0.42891621223041254
0.4244373031103246
0.42006843662344373
0.41580508500596863
0.41164303288216664
0.4075783429148821
0.4036073264759684
0.39972651942208215
0.3959326611167719
0.3922226764834868
0.3885936602644354
0.3850428632359367
0.38156767997351304
0.3781656379649656
0.37483438784672285
0.3715716946168571
0.36837542968732095
0.36524356367168226
0.3621741598173294
0.35916536800812787
0.3562154192736106
0.35332262075065035
0.3504853510507573
0.3477020559924746
0.34497124466339385
0.3422914857806492
0.33966140432235825
0.3370796784055

0.5715770755936156
0.5476263342796371
0.5276938269297616
0.510339636707039
0.4948213822786343
0.48070149951542374
0.46770091891427923
0.45562843722109597
0.44434713934736214
0.4337537857346742
0.42376821479430155
0.41432583270081447
0.4053735818836143
0.3968667797906807
0.38876732933482305
0.3810422187404278
0.3736626031765067
0.36660301015151747
0.3598408059255172
0.3533557324251198
0.3471295689156344
0.341145840980184
0.3353895936941423
0.3298471976736304
0.32450619081411364
0.3193551427293325
0.3143835406228897
0.3095816908388581
0.3049406342344302
0.3004520725298658
0.29610830410074146
0.29190216761124044
0.2878269923711702
0.28387655441192966
0.2800450374922635
0.27632699835700064
0.27271733568960455
0.2692112622829163
0.2658042800260729
0.2624921573641362
0.25927090893642607
0.2561367771405062
0.25308621540326226
0.25011587296955934
0.24722258104358816
0.24440334013895454
0.24165530851146422
0.23897579156389684
0.23636223212527074
0.23381220151850057
0.23132339134022406
0.2288936

0.6575755226728447
0.6378969458209922
0.6256077819253736
0.6127344931106551
0.6027054255632931
0.5920655315485344
0.5830769137207419
0.5739414691320504
0.5657888945778238
0.5577273717114158
0.5502699056532985
0.542993712002382
0.5361122809169749
0.5294313145210492
0.5230292003114952
0.5168177360214606
0.5108192192840025
0.5049928481908975
0.49934018749797676
0.4938410933795307
0.4884908846439584
0.4832784107070219
0.4781979889160589
0.473242517168195
0.46840684370261987
0.46368582521547247
0.45907507472585557
0.45457049785602094
0.4501683515444338
0.44586517026270633
0.4416576944223706
0.4375428789502603
0.4335178254701378
0.4295797981250245
0.42572617877022434
0.42195447663455776
0.41826230138552895
0.4146473669800554
0.41110747565446015
0.4076405182013905
0.40424446412680853
0.4009173600986285
0.39765732350709865
0.39446254014670035
0.39133125967506616
0.3882617930990671
0.38525250933378324
0.3823018327668458
0.37940824049498756
0.3765702600779059
0.373786467224865
0.3710554837677610

0.6412661197679626
0.6194530931397324
0.6040274223456851
0.5904949245647917
0.5781792687745054
0.5667692566802472
0.5561079181307499
0.5460729943012512
0.5365888135762653
0.5275862580538263
0.5190198182614998
0.5108454861152489
0.5030316198173206
0.49554726752209743
0.48836767805100684
0.48146894153768505
0.47483041795153313
0.46843262020872256
0.4622581985130807
0.45629116727906577
0.4505172647877903
0.4449236057600944
0.4394987591596763
0.4342325022835026
0.42911577223448966
0.4241404590041847
0.41929931719508606
0.4145858050745114
0.4099940017460829
0.4055184957365117
0.4011543225897324
0.3968968935652084
0.39274195241946286
0.388685530652232
0.3847239176274666
0.3808536314576125
0.37707139748119306
0.373374128062376
0.3697589063611433
0.36622297143690524
0.3627637056072818
0.35937862298005147
0.3560653594112601
0.35282166343312327
0.3496453881703594
0.346534484032853
0.3434869921359379
0.340501038333666
0.33757482780700865
0.33470664013504847
0.3318948247985246
0.3291377970656368
0

0.661210074490532
0.6377979026476006
0.6241247969595424
0.6089433840342071
0.5979130753899708
0.5863063095260342
0.5767655254710319
0.567309534325361
0.5589101304164535
0.5507883163736026
0.5432474367324596
0.53599205407557
0.5290951418062029
0.5224440580194214
0.516043964422548
0.5098491406244868
0.5038498340795255
0.49802493128540465
0.49236415182690946
0.4868558812285352
0.481491930231548
0.4762647046006541
0.4711678591972552
0.46619572295222406
0.46134319759283415
0.4566056675028174
0.45197885169346413
0.4474587991113044
0.44304179325632437
0.4387243545871381
0.43450318687806627
0.430375175735906
0.4263373584881392
0.4223869196335278
0.4185211729444543
0.41473755565823656
0.4110336169098374
0.40740701182222716
0.4038554933629863
0.4003769068855602
0.39696918397524295
0.3936303376290689
0.39035845736126856
0.38715170502976076
0.3840083108082018
0.3809265695944503
0.3779048376209147
0.37494152936106945
0.3720351146335973
0.3691841159264307
0.36638710589565
0.363642705037488
0.3609495

0.6723576882755549
0.6379580272284446
0.6250622683221572
0.6096133126746297
0.5986655275397084
0.5874045820087699
0.5777342147179961
0.568294832145088
0.55958495558388
0.5511919507539017
0.5432214708877185
0.5355411096377823
0.5281568785003091
0.5210206517637505
0.5141195237988907
0.5074315602174937
0.5009437589286038
0.49464317937280006
0.48851944973553957
0.4825633305086252
0.47676659587638687
0.4711219031616536
0.46562248887665164
0.46026219302806354
0.4550352729712234
0.4499364164394385
0.44496064344752195
0.4401033018114912
0.43536001401392915
0.43072666464330994
0.4261993687138451
0.42177445718003936
0.41744845587303087
0.41321807187119464
0.40908017820644166
0.40503180202023864
0.4010701127922846
0.3971924123806866
0.3933961256375653
0.3896787921273497
0.38603805848501277
0.38247167153501754
0.378977471981424
0.37555338866666493
0.3721974333068671
0.36890769567117526
0.36568233915034787
0.362519596679946
0.3594177669802815
0.3563752110832423
0.3533903491176181
0.3504616573286166

0.6743594085306928
0.6628817133222283
0.6544707737839233
0.6457124670563044
0.6388370357678309
0.6306391681642926
0.6246591450969018
0.6166868201679032
0.6113738992351019
0.6034367334640387
0.5985782231942067
0.5905740108264566
0.585974549026986
0.5778970072272714
0.5734002720081175
0.5653191246121501
0.5608178840122404
0.5528414240295785
0.5482753900331708
0.5405155548356331
0.5358630160080702
0.5284136862381578
0.5236819891268771
0.5166105517148457
0.5118276801619911
0.5051751632651642
0.500382723580653
0.4941678502533306
0.4894150375475669
0.48363921566569745
0.4789773094600656
0.47362910541353087
0.4691063049576454
0.46416491768276175
0.4598216728084001
0.4552594577892622
0.4511247609923877
0.44690912831704244
0.4429983863017397
0.43909349147968246
0.43540846948120043
0.4317770336657718
0.4283079307342816
0.42491328477738055
0.42164239630931444
0.4184505423920407
0.4153564931963558
0.412337785746789
0.4093992420487655
0.4065293262429224
0.4037274559215991
0.400987339207675
0.398306

0.6417339550304251
0.5977980311072075
0.576708453192995
0.5569545095677902
0.5427341731678637
0.5300323373076496
0.5192720376537515
0.509518667445221
0.5006312099085295
0.4923503399549836
0.4845633415994354
0.47717744838234144
0.470133939160535
0.4633892472759195
0.4569107580292353
0.45067282618428256
0.4446545583879016
0.4388385519143723
0.43320998981156417
0.4277560927555782
0.4224656948876473
0.41732895037320283
0.4123371003206639
0.4074822969270198
0.40275746181713806
0.39815617385535634
0.3936725774848487
0.3893013079261396
0.3850374291117469
0.38087638194289847
0.3768139406983943
0.3728461760822049
0.3689694236590551
0.365180256729792
0.36147546287983245
0.3578520235947429
0.3543070964516225
0.35083799948850236
0.3474421974257026
0.3441172894706866
0.3408609984836176
0.33767116131769387
0.3345457201781613
0.33148271486823666
0.3284802758101596
0.3255366177460824
0.3226500340372194
0.3198188914911227
0.31704162565655636
0.3143167365335499
0.3116427846530727
0.3090183874866148
0.30

0.6694001604875864
0.6527202953188165
0.6399368297023357
0.6294239641471081
0.6203415464675803
0.6122374305914892
0.6048543086995176
0.598036000053283
0.5916809705334096
0.5857186058829518
0.5800967198115671
0.5747747553976545
0.5697199454435675
0.5649050498374414
0.5603069561052442
0.5559057669104288
0.5516841721725277
0.5476269946247464
0.5437208461689718
0.5399538586525794
0.5363154671593212
0.532796232045705
0.5293876906541791
0.526082232437535
0.5228729929669349
0.5197537634220395
0.5167189129258831
0.5137633216295484
0.5108823228524174
0.5080716528898551
0.5053274073401149
0.5026460029940476
0.5000241444866915
0.49745879503717527
0.4949471507084814
0.4924866177058188
0.4900747923050462
0.48770944306335945
0.48538849501544423
0.4831100156011633
0.48087220210699827
0.4786733704340127
0.476511945030978
0.47438644985327805
0.47229550022689654
0.47023779551274825
0.4682121124802361
0.46621729931060474
0.4642522701606872
0.4623160002262721
0.4604075212517705
0.45852591743928967
0.45667

0.5858303102492848
0.5472440183424835
0.5245287828031089
0.5070567473586151
0.49282834335684655
0.48058923191216263
0.46996131828910626
0.46047491486066966
0.45194640968309596
0.4441416096130021
0.4369296679319505
0.4301866051554447
0.4238306236256666
0.4177965918715172
0.4120381050332346
0.4065196038681436
0.4012140717809441
0.3961001332461701
0.3911605659096829
0.38638113616228686
0.3817498759974598
0.37725656107925015
0.3728923444037953
0.36864948519185925
0.36452114320726847
0.3605012208635904
0.35658423880041473
0.35276523777912
0.3490396999054553
0.3454034852867172
0.3418527804669621
0.3383840562768645
0.3349940330561319
0.3316796517845518
0.3284380499219062
0.3252665410460739
0.3221625975590447
0.31912383589023485
0.31614800374154417
0.3132329690126386
0.310376710116883
0.30757730745574724
0.30483293586449517
0.3021418578777167
0.2995024176915918
0.2969130357223547
0.2943722036784357
0.2918784800781913
0.2894304861567129
0.2870269021145388
0.28466646366864207
0.2823479588721892


In [62]:
X_test=(X_test-mean)/std
z=np.matmul(w_outr,X_test.T) + b_outr
a=compute_sigmoid(z)
a=a.T

In [63]:
print(a.shape)
   

(5000, 10)


In [64]:
y_pred=np.zeros(5000)
for i in range(5000):
    y_pred[i]=(np.argmax(a[i]))


In [65]:
print(y_pred)

[4. 1. 8. ... 7. 0. 3.]


In [66]:
accuracy=0
for i in range(5000):
    if(y_pred[i]==y_test[i,1]):
        accuracy+=1
print(accuracy/50)

80.46
