In [6]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
# reading the data
df = pd.read_csv('classification_train.csv')
temp = df.to_numpy()
X_train = temp[:,2:787]
m = X_train.shape[0]
y_train = temp[:,0:2]
y_new = np.zeros(m)
print(X_train.shape)

(30000, 784)


In [26]:
def zscore(X_in):
    mu     = np.mean(X_in, axis=0)                 
    sigma  = np.std(X_in, axis=0)                
    X_norm = (X_in - mu) / sigma 
    X_op = X_in/255
    return X_op

In [8]:
# initialise the pararmeters
# dimension of n layer = dim_of_n
def ini_weight(dim_of_n):
    L = len(dim_of_n)
    W = {}
    B ={}
    for i in range(1,L):
        W['w'+ str(i)] = np.random.randn(dim_of_n[i],dim_of_n[i-1])
        B['b'+ str(i)] = np.random.randn(dim_of_n[i],1)
    
    return W,B


In [9]:
a,b = ini_weight([784,])
print(a["w1"].T.shape)

KeyError: 'w1'

In [19]:
# computoing the sigmoid fucntion and ReLU
def compute_sigmoid(a_in,w,b):
    z = np.matmul(a_in,w.T) + b.T
    a = 1/(1+np.exp(-z))
    data = w,a_in,b
    return a,data
def compute_ReLU(a_in,w,b):
    z = np.matmul(a_in,w.T) + b.T
    a = np.max(z,0)
    data = w,a_in,b
    return a,data

    

In [53]:
#forward propagation
def forward_prop(X, dim_of_n):
    c_data = []
    L = len(dim_of_n)                 
    A = X
    W,B = ini_weight(dim_of_n)
    for l in range(1, L-1):
        A_out = A
        A, data = compute_ReLU(A_out, W['w' + str(l)], B['b' + str(l)] )
        c_data.append(data)

    A, data = compute_sigmoid(A, W['w' + str(L-1)], B['b' + str(L-1)] )
    c_data.append(data)
            
    return A, c_data




In [54]:
# compute cost 
def cost(A,y_train):
     cost = (-1/m) * (np.dot(y_train, np.log(A).T) + np.dot((1-y_train), np.log(1-A).T))

In [55]:
# creating 10 different y labels
m = y_train.shape[0]
for i in range(10):
    for j in range(m):
        if y_train[j][1] == i:
            y_new[j] = 1
        else:
            y_new[j] = 0 
    y_train = np.hstack((y_train, np.atleast_2d(y_new).T))
y_ntrain = y_train
print(y_ntrain[:,2:13])

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [63]:
a,b = forward_prop(zscore(X_train),[784,60,5,1])



(array([[0.7573596 , 0.01871603, 0.25348047, 0.9796474 , 0.27882611]]),
 array([-260.56171712,   -6.63111793,  303.1463501 ,  196.22481421,
        -164.65101947]),
 array([[0.12537706]]))

In [66]:
# calculating gradients
def gradients(dZ, data):
    A_prev, W, b = data
    m = A_prev.shape[1]
    dW = (1/m) * np.dot(dZ, A_prev.T)
    db = (1/m) * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W.T,dZ)
    return dW,db,dA_prev

In [64]:
#computing relu and sigmoid backward 
def compute_backward_ReLU(dA):
    if dA > 0 :
        dZ = 1 
    else 
        dZ = 0
    
def compute_backward_sigmoid(dA):
    dZ = 
    

IndentationError: expected an indented block (2852100380.py, line 3)

In [65]:
def backward_prop(AL, Y, data):

    gradients = {}
    L = len(data) 
    m = AL.shape[1]
    
    dZL = 1/m*(AL-Y)
    present_data = data[L]
    gradients["dA" + str(L)], gradients["dW" + str(L)], gradients["db" + str(L)] = compute_sigmoid(dAL, present_data)

    for l in reversed(range(L-1)):
        current_data = data[l]
        dA_p, dW_p, db_p = compute_ReLU(grads["dA" + str(l + 1)], present_data)
        grads["dA" + str(l)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp

    return gradients

In [ ]:
def update_parameters(parameters, grads, learning_rate):
    L = len(parameters)
    for l in range(L):
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)]
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]
    return parameters
