In [25]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [50]:
# reading the data
df = pd.read_csv('classification_train.csv')
temp = df.to_numpy()
X_train = temp[:,2:787]
m = X_train.shape[0]
y_train = temp[:,0:2]
y_new = np.zeros(m)
print(X_train.shape)

(30000, 784)


In [51]:
def zscore(X_in):
    mu     = np.mean(X_in, axis=0)                 
    sigma  = np.std(X_in, axis=0)                
    X_norm = (X_in - mu) / sigma 
    X_op = X_in/255
    return X_op

In [52]:
# initialise the pararmeters
# dimension of n layer = dim_of_n
def ini_weight(dim_of_n):
    L = len(dim_of_n)
    W = {}
    B ={}
    for i in range(1,L):
        W[i] = np.random.randn(dim_of_n[i],dim_of_n[i-1])
        B[i] = np.random.randn(dim_of_n[i],1)
    
    return W,B


In [53]:
w,b = ini_weight([784,10,10])

In [54]:
# computoing the sigmoid fucntion and ReLU
def compute_sigmoid(a_in,w,b):
    z = np.matmul(a_in,w.T) + b.T
    a = 1/(1+np.exp(-z))
    return a
def compute_ReLU(a_in,w,b):
    z = np.matmul(a_in,w.T) + b.T
    a = np.max(z,0)
    return a
def RelU_derivative(z):
    return (z>0)

    

In [60]:
#forward propagation
def forward_prop(x, w, b):
    L = len(w)+1                 
    A ={}
    Z={}
    A[0]=x
    
    for l in range(1, L-1):
        A[l]=compute_ReLU(A[l-1],w[l],b[l])
    A[L-1] = compute_sigmoid(A[L-2],w[L-1],b[L-1])
    return A




In [61]:
# compute cost 
def cost(A,y_train):
     cost = (-1/m) * (np.dot(y_train, np.log(A).T) + np.dot((1-y_train), np.log(1-A).T))

In [58]:
# creating 10 different y labels
m = y_train.shape[0]
for i in range(10):
    for j in range(m):
        if y_train[j][1] == i:
            y_new[j] = 1
        else:
            y_new[j] = 0 
    y_train = np.hstack((y_train, np.atleast_2d(y_new).T))
y_ntrain = y_train
print(y_ntrain[:,2:13])

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [63]:
a = forward_prop(zscore(X_train),w,b)
print(a)

{0: array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 1: array([21.06764994, 39.34423285, 45.41008879, 35.35463286, 48.37144142,
       23.2855989 , 27.47148063, 33.25827554, 26.4489741 , 57.07486792]), 2: array([[6.06986978e-60, 4.14418463e-11, 1.00000000e+00, 1.00000000e+00,
        1.25500828e-06, 1.00000000e+00, 1.00000000e+00, 6.36263101e-27,
        1.38346606e-29, 1.00000000e+00]])}
